# Generated by Django 6.0.1 on 2026-01-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dashboard_permission', models.CharField(choices=[('none', 'none'), ('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('full', 'full')], default='view', max_length=20)),
                ('pilgrims_permission', models.CharField(choices=[('none', 'none'), ('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('full', 'full')], default='none', max_length=20)),
                ('payments_permission', models.CharField(choices=[('none', 'none'), ('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('full', 'full')], default='none', max_length=20)),
                ('expenses_permission', models.CharField(choices=[('none', 'none'), ('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('full', 'full')], default='none', max_length=20)),
                ('treasury_permission', models.CharField(choices=[('none', 'none'), ('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete'), ('full', 'full')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_role',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('custom', 'Custom Role')], default='custom', help_text="Type de rôle de l'utilisateur", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Rôle personnalisé si role_type=custom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
    ]
